### ISSUE TITLE
Execute other tasks before build

### ISSUE THREAD

**Issue by kwiat1990** [xRealNeon/VuePagesAction#5]
Hi, 

I would like to execute some other commands before the Vue app will be build such as unit tests and so one. Is it possible with action or can I use some other action first followed by this one?

**Comment by xRealNeon** [comment]
Hey, you can just add the test command to your action yml file like this
```yml
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run test:unit
```
